name: PHP Composer

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate composer.json
      run: composer validate
    - name: Installing Dependencies
      run: composer install --no-dev
    - name: Test Running
      run: php public/index.php

